<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Código*</label>
              <input type="text" name="codigo" id="txt_codigo" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Producto*</label>
              <input type="text" name="nombre_producto" id="txt_nombre_producto" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Marca*</label>
              <input type="text" name="marca" id="txt_marca" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Precio*</label>
              <input type="text" name="precio" id="txt_precio" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Cantidad*</label>
              <input type="text" name="cantidad" id="txt_cantidad" required class="form-control">
        </div>
    </div>
</div>