<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Precio*</label>
              <input type="text" name="precio" id="txt_precio" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Stock*</label>
              <input type="text" name="stock" id="txt_stock" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
         <div class="form-group">
            <label>Categoria*</label>
            <?php 
                $categoriaJson = file_get_contents("./resources/assets/js/categoria.json");
                $categoriasData = json_decode($categoriaJson, true);
            ?>
            <select class="form-control" id="slct_categoria" name="categoria">
              <option value="">Seleccione</option>
            <?php 
                  foreach ($categoriasData as $key => $value) { 
                    if ($value["deleted_at"] == "") { ?>
                    <option value= "<?php echo $value['tipo']; ?>" > <?php echo $value['tipo']; ?> </option>
                   <?php }
                  }
            ?>
            </select>
        </div>
    </div>    
</div>