<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label>Unidad*</label>
            <select class="form-control" name="unidad" id="slct_unidad" >
                <option value="">Seleccione</option>
                <option value="Unidad">Unidad</option>
                <option value="Decena">Decena</option>
                <option value="Docena">Docena</option>
                <option value="Ciento">Ciento</option>
                <option value="Millar">Millar</option>
            </select>
        </div>
    </div>    
    <div class="col-md-12">
        <div class="form-group">
              <label>Precio*</label>
              <input type="text" name="precio" id="txt_precio" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Stock*</label>
              <input type="text" name="stock" id="txt_stock" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label>Categoria*</label>
            <select class="form-control" name="categoria" id="slct_categoria" >
                <option value="">Seleccione</option>
                <option value="Útiles">Útiles</option>
            </select>
        </div>
    </div>    
</div>