<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Código*</label>
              <input type="text" name="codigo" id="txt_codigo" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Perfil*</label>
              <input type="text" name="perfil" id="txt_perfil" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Descripción*</label>
              <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label>Estado*</label>
            <select class="form-control" id="slct_estado" name="estado">
                <option value="">Seleccione</option>
                <option value="Activo">Activo</option>
                <option value="Inactivo">Inactivo</option>
            </select>
        </div>
    </div>
</div>