<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Código*</label>
              <input type="text" name="codigo" id="txt_codigo" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Categoria*</label>
              <input type="text" name="categoria" id="txt_categoria" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Descripcion*</label>
              <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
        </div>
    </div>
</div>