<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Precio*</label>
              <input type="text" name="precio" id="txt_precio" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Stock*</label>
              <input type="text" name="stock" id="txt_stock" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label>Categoria*</label>
            <select class="form-control" name="categoria" id="slct_categoria" >
                <option value="">Seleccione</option>
                <option value="PC">PC</option>
                <option value="Laptop">Laptop</option>
                <option value="Monitor">Monitor</option>
                <option value="Mouse">Mouse</option>
                <option value="Teclado">Teclado</option>
                <option value="Teléfono">Teléfono</option>
                <option value="Impresora">Impresora</option>
            </select>
        </div>
    </div>    
</div>