<div class="row">
   
   <div class="col-md-12">
        <div class="form-group">
              <label>Nombres*</label>
              <input type="text" name="nombre" id="txt_nombre" required class="form-control">
        </div>
    </div> 
    
    <div class="col-md-12">
        <div class="form-group">
              <label>Descripcion*</label>
              <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
        </div>
    </div>
        
    <div class="col-md-12">
        <div class="form-group">
              <label>Area*</label>
              <input type="text" name="area" id="txt_area" required class="form-control">
        </div>
    </div>
    
</div>