<div class="row">
   <div class="col-md-12">
        <div class="form-group">
              <label>DNI*</label>
              <input type="text" name="dni" id="txt_dni" required class="form-control">
        </div>
    </div>
   <div class="col-md-12">
        <div class="form-group">
              <label>Nombres*</label>
              <input type="text" name="nombres" id="txt_nombres" required class="form-control">
        </div>
    </div> 
    
    <div class="col-md-12">
        <div class="form-group">
              <label>Apellidos*</label>
              <input type="text" name="apellidos" id="txt_apellidos" required class="form-control">
        </div>
    </div>
    <!--
    <div class="col-md-12">
        <div class="form-group">
              <label>Ap. Materno*</label>
              <input type="text" name="ape_materno" id="txt_ape_materno" required class="form-control">
        </div>
    </div>
    -->
    <div class="col-md-12">
        <div class="form-group">
            <label>Sexo*</label>
            <select class="form-control" id="slct_sexo" name="sexo">
                <option value="">Seleccione</option>
                <option value="Masculino">Masculino</option>
                <option value="Femenino">Femenino</option>
            </select>
        </div>
    </div>
    
    <div class="col-md-12">
        <div class="form-group">
              <label>Fecha Nacimiento*</label>
              <input type="text" name="fecha_Nac" id="txt_fecha_Nac" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Direccion*</label>
              <input type="text" name="direccion" id="txt_direccion" required class="form-control">
        </div>
    </div>
     <div class="col-md-12">
        <div class="form-group">
              <label>N° Telefono*</label>
              <input type="text" name="numero_telefono" id="txt_numero_telefono" required class="form-control">
        </div>
    </div>
   <!--
    <div class="col-md-12">
        <div class="form-group">
              <label>Carrera*</label>
              <input type="text" name="carrera" id="txt_carrera" required class="form-control">
        </div>
    </div>
   -->
</div>