<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Nombres*</label>
              <input type="text" name="nombres" id="txt_nombres" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Descripcion*</label>
              <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Estado*</label>
              <input type="text" name="estado" id="txt_estado" required class="form-control">
        </div>
    </div>
<!--
    <div class="col-md-12">
        <div class="form-group">
            <label>Sexo*</label>
            <select class="form-control" id="slct_sexo" name="sexo">
                <option value="">Seleccione</option>
                <option value="Masculino">Masculino</option>
                <option value="Femenino">Femenino</option>
            </select>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Posicion*</label>
              <input type="text" name="posicion" id="txt_posicion" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Area*</label>
              <input type="text" name="area" id="txt_area" required class="form-control">
        </div>
    </div>
     <div class="col-md-12">
        <div class="form-group">
              <label>Fecha de Ingreso*</label>
              <input type="text" name="start_date" id="txt_start_date" required class="form-control">
        </div>
    </div>

  -->  




</div>