<div class="row">
    <div class="col-md-12">
        <div class="form-group">
              <label>Código*</label>
              <input type="text" name="codigo" id="txt_codigo" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Marca*</label>
              <input type="text" name="marca" id="txt_marca" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Modelo*</label>
              <input type="text" name="modelo" id="txt_modelo" required class="form-control">
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
              <label>Serie*</label>
              <input type="text" name="serie" id="txt_serie" required class="form-control">
        </div>
    </div>
</div>