<!-- Modal -->
<div class="modal fade" id="mdlPerfil" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Perfiles</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form id="form-perfil" method="POST" url="functions/perfil_class.php">
              <div class="tab-content" id="myTabContent">
                  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                      <div class="row">
                          <div class="col-md-12">
                              <div class="form-group">
                                    <label>Perfil*</label>
                                    <input type="text" name="perfil" id="txt_perfil" required class="form-control">
                              </div>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-12">
                              <div class="form-group">
                                    <label>Descripción*</label>
                                    <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
                              </div>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-12">
                              <div class="form-group">
                                  <label>Estado*</label>
                                  <select class="form-control" id="slct_estado" name="estado">
                                      <option value="">Seleccione</option>
                                      <option value="Activo">Activo</option>
                                      <option value="Inactivo">Inactivo</option>
                                  </select>
                              </div>
                          </div>
                      </div>
                  </div>
             </div>
              <input type="hidden" name="id" id="txt_id" value="">
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="btn-guardar">Guardar</button>
      </div>
    </div>
  </div>
</div>