<!-- Modal -->
<div class="modal fade" id="mdlEmpresa" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Empresa</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="form-empresa" method="POST" url="functions/usuario_class.php">
          <div class="row">
              <div class="col-md-12">
                  <div class="form-group">
                        <label>Nombres*</label>
                        <input type="text" name="nombres" id="txt_nombres" required class="form-control">
                  </div>
              </div>
              <div class="col-md-12">
                  <div class="form-group">
                        <label>Ape Paterno*</label>
                        <input type="text" name="ape_paterno" id="txt_ape_paterno" required class="form-control">
                  </div>
              </div>
              <div class="col-md-12">
                  <div class="form-group">
                        <label>Ape Materno*</label>
                        <input type="text" name="ape_materno" id="txt_ape_materno" required class="form-control">
                  </div>
              </div>
              <div class="col-md-12">
                  <div class="form-group">
                      <label>Sexo*</label>
                      <select class="form-control" id="slct_sexo" name="sexo">
                          <option value="">Seleccione</option>
                          <option value="Masculino">Masculino</option>
                          <option value="Femenino">Femenino</option>
                      </select>
                  </div>
              </div>
          </div>
          <input type="hidden" name="id" id="txt_id" value="">
        </form> 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>