<!-- Modal -->
<div class="modal fade" id="mdlUsuario" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Usuario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <form>
              <div class="row">
                <div class="col-md-12"> 
                  <div class="form-group">
                    <label>Nombres*</label>
                    <input type="text" name="nombres" id="text_nombres" required>
                  </div>
                </div>
                <div class="form-group">
                  <label>Ape Paterno*</label>
                  <input type="text" name="ape_paterno" id="text_ape_paterno" required>
                </div>
                <div class="form-group">
                  <label>Ape Materno*</label>
                  <input type="text" name="ape_materno" id="text_ape_materno" required>
                </div>
                <div class="form-group">
                  <label>Sexo*</label>
                  <input type="text" name="sexo" id="text_sexo" required>
                </div>
              </div>
            </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary">Guardar</button>
      </div>
    </div>
  </div>
</div>