<!-- Modal -->
<div class="modal fade" id="mdlEmpresa" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Empresa</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <form>
              <div class="row">
                <div class="col-md-12"> 
                  <div class="form-group">
                    <label>Razon Social*</label>
                    <input type="text" name="razon social" id="text_razon_social" required>
                  </div>
                </div>
                <div class="col-md-12"> 
                  <div class="form-group">
                    <label>RUC*</label>
                    <input type="text" name="ruc" id="text_ruc" required>
                  </div>
                </div>
                <div class="col-md-12"> 
                  <div class="form-group">
                    <label>Direccion*</label>
                    <input type="text" name="direccion" id="text_direccion" required>
                  </div>
                </div>
                <div class="col-md-12"> 
                  <div class="form-group">
                    <label>Ultima Actualizacion*</label>
                    <input type="text" name="ultima_actualizacion" id="text_ultima_actualizacion" required>
                  </div>
                </div>
                <div class="col-md-12"> 
                  <div class="form-group">
                    <label>Estado*</label>
                    <input type="text" name="estado" id="text_estado" required>
                  </div>
                </div>
              </div>
            </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary">Guardar</button>
      </div>
    </div>
  </div>
</div>