<!-- Modal -->
<div class="modal fade" id="mdlProducto" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Producto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form id="form-usuario" method="POST" url="functions/usuario_class.php">
              <input type="hidden" name="id" id="txt_id" value="">
              <div class="row">
                  <div class="col-md-12">
                      <div class="form-group">
                        <label>Codigo*</label>
                        <input type="text" name="codigo" id="txt_codigo" required class="form-control">
                    </div>
                  </div>
                  <div class="col-md-12">
                      <div class="form-group">
                        <label>Descripcion*</label>
                        <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
                    </div>
                  </div>
                  <div class="col-md-12">
                       <div class="form-group">
                          <label>Modelo*</label>
                          <input type="text" name="modelo" id="txt_modelo" required class="form-control">
                      </div>
                  </div>
                  <div class="col-md-12">
                      <div class="form-group">
                        <label>Color*</label>
                        <select class="form-control" id="slct_color" name="color">
                            <option value="Seleccione"></option>
                            <option value="Amarillo">Amarillo</option>
                            <option value="Marrón">Marrón</option>
                            <option value="Rojo">Rojo</option>
                            <option value="Verde">Verde</option>
                            <option value="Azul">Azul</option>
                            <option value="Caoba">Caoba</option>
                        </select>
                      </div>
                  </div>
                  <div class="col-md-12">
                       <div class="form-group">
                          <label>Stock*</label>
                          <input type="text" name="stock" id="txt_stock" required class="form-control">
                      </div>
                  </div>
                  <div class="col-md-12">
                      <div class="form-group">
                        <label>Categoria*</label>
                        <select class="form-control" id="slct_categoria" name="categoria">
                            <option value="Seleccione"></option>
                            <option value="Hogar">Hogar</option>
                            <option value="Limpieza">Limpieza</option>
                        </select>
                      </div>
                  </div>
                  <div class="col-md-12">
                      <div class="form-group">
                        <label>Estado*</label>
                        <select class="form-control" id="slct_estado" name="estado">
                            <option value="Seleccione"></option>
                            <option value="Activo">Activo</option>
                            <option value="Inactivo">Inactivo</option>
                        </select>
                      </div>
                  </div>
                  
              </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="btn-guardar">Guardar</button>
      </div>
    </div>
  </div>
</div>