<!-- Modal -->
<div class="modal fade" id="mdlProducto" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Usuario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form id="form-producto" method="POST" url="functions/producto_class.php">
              <input type="hidden" name="id" id="txt_id" value="">
              <div class="row">
                  <div class="col-md-12">
                      <div class="form-group">
                        <label>Nombre*</label>
                        <input type="text" name="nombre" id="txt_nombre" required class="form-control">
                    </div>
                  </div>
                  <div class="col-md-12">
                      <div class="form-group">
                        <label>Descripcion*</label>
                        <input type="text" name="descripcion" id="txt_descripcion" required class="form-control">
                    </div>
                  </div>
                  <div class="col-md-12">
                      <div class="form-group">
                        <label>Estado*</label>
                        <select class="form-control" id="slct_estado" name="estado" required="required">
                            <option value="Seleccione"></option>
                            <option value="Activo">Activo</option>
                            <option value="Inactivo">Inactivo</option>
                        </select>
                      </div>
                  </div>
                  
              </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="btn-guardar">Guardar</button>
      </div>
    </div>
  </div>
</div>