<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="#">Navbar</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
		    <li class="nav-item active">
		        <a class="nav-link" href="/home.php">Inicio <span class="sr-only">(current)</span></a>
		    </li>
	      	<li class="nav-item">
	        	<a class="nav-link" href="/producto.php">Producto</a>
	      	</li>
	      	<li class="nav-item">
	        	<a class="nav-link" href="/categoria.php">Categoria</a>
	      	</li>
	      	<li class="nav-item">
	        	<a class="nav-link" href="/empleado.php">Empleado</a>
	      	</li>
	      	<li class="nav-item">
	        	<a class="nav-link" href="/usuario.php">Usuario</a>
	      	</li>
	      	<li class="nav-item">
	        	<a class="nav-link" href="/perfil.php">Perfil</a>
	      	</li>
	    </ul>
	    <form class="form-inline my-3 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Buscar..." aria-label="Buscar...">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
	      <a class="btn btn-danger my-2 my-sm-0 mx-sm-2" href="logout.php">Salir</a>
	    </form>
	  </div>
	</nav>
</header>