<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
		    <li class="nav-item active">
		        <a class="nav-link" href="/home.php">Inicio <span class="sr-only">(current)</span></a>
		    </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Mantenimiento
	        </a>
	        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item" href="/producto.php">Productos</a>
	          <a class="dropdown-item" href="/categorias.php">Categorias</a>
	          <a class="dropdown-item" href="/empleado.php">Empleados</a>
	          <a class="dropdown-item" href="/perfil.php">Perfiles</a>
	          <a class="dropdown-item" href="/usuario.php">Usuarios</a>
	        </div>
	      </li>
	    </ul>
	    <form class="form-inline my-3 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Buscar..." aria-label="Buscar...">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
	      <a class="btn btn-danger my-2 my-sm-0 mx-sm-2" href="logout.php">Salir</a>
	    </form>
	  </div>
	</nav>
</header>